#!/bin/zsh

## Aliases ##
# Utility commands
alias ls='lsd -X --group-dirs first'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'

alias mkdir='mkdir -pv'
alias back='cd $OLDPWD'
alias :q='exit'

# System
alias grub-edit='doasedit /etc/default/grub'
alias grub-update='doas grub-mkconfig -o /boot/grub/grub.cfg'

# Other commands
alias neo='nvim'
alias bat='bat --number --theme base16'
alias cat='bat -p'
alias wget='wget --hsts-file=${XDG_DATA_HOME}/.wget-hsts'
alias ytdl='yt-dlp -f "bv*+ba/b" -o "~/Downloads/%(title)s.%(ext)s"'
alias ytdla='yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 -o "~/Downloads/%(title)s.%(ext)s"'
alias rm='trash'
alias ip='ip --color=auto'
alias gdu='gdu --si'
alias rr='curl -sL http://bit.ly/10hA8iC | bash'

# GIT Aliases
alias gits='git status'
alias gitss='git status --short'
alias gita='git add'
alias gitd='git diff'
alias gitr='git restore'
alias gitrs='git restore --staged'

giti() {
  echo "$1" >>"$PWD/.gitignore"
}

## Functions ##
y() {
  tmp="$(mktemp -t yazi-cwd.XXXXX)"
  yazi --cwd-file "$tmp" "$@"
  cd "$(cat "$tmp")" || return
  /bin/rm "$tmp"
}

cz() {
  case "$1" in
    apply|update|diff)
      if ! bw login --check >/dev/null; then
        BW_SESSION="$(bw login --raw)"
      else
        BW_SESSION="$(bw unlock --raw)"
      fi
      export BW_SESSION
      ;;
  esac
  chezmoi "$@"
}

fix-pacman() {
  if [[ "$1" == "nopgp" ]]; then
    doas rm -r /var/lib/pacman/sync
    doas pacman -Syy
  elif [[ "$1" == "unlockdb" ]]; then
    doas rm /var/lib/pacman/db.lck
  fi
}

nmwifi() {
  case $1 in
  l | list | -l | --list)
    nmcli device wifi list
    ;;
  c | connect | -c | --connect)
    nmcli device wifi connect "$2"
    ;;
  esac
}

bt() {
  [[ -n "$2" ]] && MAC_ADRESS="$(bluetoothctl devices | grep "$2" | awk '{print $2}')"
  case $1 in
  l | list)
    bluetoothctl devices
    ;;
  lc | list-connected)
    bluetoothctl devices Connected
    ;;
  c | connect)
    bluetoothctl connect "$MAC_ADRESS"
    ;;
  d | disconnect)
    bluetoothctl disconnect "$MAC_ADRESS"
    ;;
  t | toggle)
    DEVICES_CONNECTED="$(bluetoothctl devices Connected | awk '{print $2}')"
    if grep -q "$MAC_ADRESS" <<<"${DEVICES_CONNECTED[@]}"; then
      bluetoothctl disconnect "$MAC_ADRESS"
    else
      bluetoothctl connect "$MAC_ADRESS"
    fi
    ;;
  esac
}

cleanup() {
  if [[ -n "$(pacman -Qtdq)" ]]; then
    pacman -Qtdq | doas pacman -Rns -
  fi
  if command -v paru &>/dev/null; then
    paru -Sc
  fi
  flatpak remove --unused
  docker image prune
  trash-empty
}

video-wallpaper() {
  VIDEO_PATH="/tmp/video.webm"
  [[ -f "$VIDEO_PATH" ]] && rm "$VIDEO_PATH"
  ytdl -o "$VIDEO_PATH" "$1" &&
    mpvpaper -f -o "no-audio loop --speed=3" eDP-1 "$VIDEO_PATH"
}

## Programing ##
# Bash
mksh() {
  if [[ ! -e "$1" ]]; then
    if [[ -d $(dirname "$1") ]]; then
      echo -e "#!/bin/sh\n\n" >"$1"
      chmod +x "$1"
      if [[ "$2" = "-e" ]]; then
        neo "$1"
      fi
    fi
  fi
}

# Dev Script
# shellcheck disable=SC1091
source "$HOME/scripts/dev"
